coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        if_ci_failed: error
        only_pulls: false
    patch:
      default:
        target: auto
        threshold: 0%
        if_ci_failed: error
        only_pulls: false
