version: '3.2'

services:
  caseworker:
    depends_on:
      - redis
      - api
    build:
      context: .
      dockerfile: Dockerfile.e2e
    environment:
      # Below values can be found in vault
      DIRECTORY_SSO_API_CLIENT_BASE_URL: ${PW_DIRECTORY_SSO_API_CLIENT_BASE_URL}
      DIRECTORY_SSO_API_CLIENT_API_KEY: ${PW_DIRECTORY_SSO_API_CLIENT_API_KEY}
      AUTHBROKER_CLIENT_ID: ${PW_AUTHBROKER_CLIENT_ID}
      AUTHBROKER_CLIENT_SECRET: ${PW_AUTHBROKER_CLIENT_SECRET}
      TEST_SSO_EMAIL: ${TEST_SSO_EMAIL}
      TEST_SSO_PASSWORD: ${TEST_SSO_PASSWORD}
      PW_SSO_USER: ${PW_SSO_USER}
      PW_EXPORT_SSO_USER: ${PW_EXPORT_SSO_USER}
      PW_SSO_PASSWORD: ${PW_SSO_PASSWORD}
      PW_SSO_URL: ${PW_SSO_URL}
      AWS_ACCESS_KEY_ID: ${PW_AWS_ACCESS_KEY_ID}
      AWS_REGION: ${PW_AWS_REGION}
      AWS_SECRET_ACCESS_KEY: ${PW_AWS_SECRET_ACCESS_KEY}
      AWS_STORAGE_BUCKET_NAME: ${PW_AWS_STORAGE_BUCKET_NAME}
      AUTH_USER_NAME: ${AUTH_USER_NAME}
      AUTH_USER_PASSWORD: ${AUTH_USER_PASSWORD}
      BASIC_AUTH_ENABLED: ${BASIC_AUTH_ENABLED}
      BROWSER_HOSTS: ${BROWSER_HOSTS_CASEWORKER}
      ENDPOINT: ${ENDPOINT}
    env_file:
      - ./caseworker.env
    ports:
      - 8200:8200
    volumes:
      - ./playwright_videos:/app/playwright_videos
    entrypoint: ["/bin/sh","-c"]
    command:
    - |
      dockerize -wait tcp://api:8100 -timeout 5m
      npm run build_caseworker
      ./manage.py runserver 0.0.0.0:${PORT:-8200}
    stdin_open: true
    tty: true
